# Generated by Django 4.2.3 on 2023-12-03 23:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import fichario.synchronization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('hash', models.CharField(default=fichario.synchronization.models.create_hash, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(editable=False, max_length=100)),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF00', 'No color'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#FF0000FF', 'Red'), ('#800000FF', 'Maroon'), ('#8b4513FF', 'Brown'), ('#918151FF', 'Tan'), ('#f94d00FF', 'Orange'), ('#ffe5b4FF', 'Peach'), ('#fcc200FF', 'Gold'), ('#ffff00FF', 'Yellow'), ('#00ff00FF', 'Lime'), ('#556b2fFF', 'Olive'), ('#008000FF', 'Green'), ('#7fffd4FF', 'Aquamarine'), ('#367588FF', 'Teal Blue'), ('#00ffffFF', 'Cyan'), ('#87ceebFF', 'Sky Blue'), ('#0000ffFF', 'Blue'), ('#000070FF', 'Navy Blue'), ('#800080FF', 'Purple'), ('#8a2be2FF', 'Violet'), ('#da70d6FF', 'Orchid'), ('#dcd0ffFF', 'Lavender')], default='#FFFFFF00', image_field=None, max_length=25, samples=None)),
                ('author', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('edition', models.CharField(blank=True, max_length=300)),
                ('tags', models.ManyToManyField(blank=True, to='annotations.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('hash', models.CharField(default=fichario.synchronization.models.create_hash, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(editable=False, max_length=100)),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF00', 'No color'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#FF0000FF', 'Red'), ('#800000FF', 'Maroon'), ('#8b4513FF', 'Brown'), ('#918151FF', 'Tan'), ('#f94d00FF', 'Orange'), ('#ffe5b4FF', 'Peach'), ('#fcc200FF', 'Gold'), ('#ffff00FF', 'Yellow'), ('#00ff00FF', 'Lime'), ('#556b2fFF', 'Olive'), ('#008000FF', 'Green'), ('#7fffd4FF', 'Aquamarine'), ('#367588FF', 'Teal Blue'), ('#00ffffFF', 'Cyan'), ('#87ceebFF', 'Sky Blue'), ('#0000ffFF', 'Blue'), ('#000070FF', 'Navy Blue'), ('#800080FF', 'Purple'), ('#8a2be2FF', 'Violet'), ('#da70d6FF', 'Orchid'), ('#dcd0ffFF', 'Lavender')], default='#FFFFFF00', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=300)),
                ('tags', models.ManyToManyField(blank=True, to='annotations.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('hash', models.CharField(default=fichario.synchronization.models.create_hash, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(editable=False, max_length=100)),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF00', 'No color'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#FF0000FF', 'Red'), ('#800000FF', 'Maroon'), ('#8b4513FF', 'Brown'), ('#918151FF', 'Tan'), ('#f94d00FF', 'Orange'), ('#ffe5b4FF', 'Peach'), ('#fcc200FF', 'Gold'), ('#ffff00FF', 'Yellow'), ('#00ff00FF', 'Lime'), ('#556b2fFF', 'Olive'), ('#008000FF', 'Green'), ('#7fffd4FF', 'Aquamarine'), ('#367588FF', 'Teal Blue'), ('#00ffffFF', 'Cyan'), ('#87ceebFF', 'Sky Blue'), ('#0000ffFF', 'Blue'), ('#000070FF', 'Navy Blue'), ('#800080FF', 'Purple'), ('#8a2be2FF', 'Violet'), ('#da70d6FF', 'Orchid'), ('#dcd0ffFF', 'Lavender')], default='#FFFFFF00', image_field=None, max_length=25, samples=None)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annotations.project')),
                ('tags', models.ManyToManyField(blank=True, to='annotations.tag')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
